name: CI
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: [ '2.6' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup ruby ${{ matrix.ruby_version }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - name: Setup cache key and directory for gems cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-use-ruby-${{ matrix.ruby_version }}-${{ hashFiles('**/Gemfile.lock') }}
      - name: Bundle install
        run: |
          gem install bundler:1.17.0
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: |
          bundle exec rake test
